title: Alfred Mastan
description: A template for your AOS C111/204 project site.
logo: /assets/IMG/template_logo.png
show_downloads: true
remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme
